---
title: "mcrigor"
output: html_document
date: "2025-12-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# trying mcrigor on different metacells under different conditions
```{r}
#tools::R_user_dir("mcRigor", which="cache")
library(mcRigor)
library(Seurat)
library(SeuratDisk)
library(SeuratData)
library(ggplot2)
library(qs)
library(Matrix)
library(dplyr)
library(SummarizedExperiment)
library(BPCells)
#library(DropletUtils)
```

```{r}
# set constants
dataset_name = 'bm'
sc_input_dir <- '/media/ResearchHome/plummgrp/home/common/Maggie/QuantumCell/metacell_clean/'
mc_input_dir <- paste0('/media/ResearchHome/plummgrp/home/common/Maggie/QuantumCell/', dataset_name, '_metacells/')
```

```{r}
# convert h5ad to seurat (for smaller h5ads)
sc_seurat <- schard::h5ad2seurat(paste0(sc_input_dir,dataset_name, '.clean.h5ad'))
```

```{r}
# for larger objects, use BPCells
if (file.exists(paste0(sc_input_dir, dataset_name, '.clean_BP'))) {
  data <- open_matrix_anndata_hdf5(paste0(sc_input_dir, dataset_name, '.clean.h5ad'))
  write_matrix_dir(
     mat = data,
     dir = paste0(sc_input_dir, dataset_name, '.clean_BP'))
} 

mat <- open_matrix_dir(dir = paste0(sc_input_dir, dataset_name, '.clean_BP'))
metadata <- read.csv(paste0(sc_input_dir, dataset_name, '_metadata.csv'), header = T, row.names = 1)

sc_seurat <- CreateSeuratObject(counts = mat, meta.data = metadata)
```

```{r}
# load metacell partitions
cell_membership_all <- read.csv(file = paste0(mc_input_dir, 'with_lateral/cell_membership.csv'), check.names = F, row.names = 1)
head(cell_membership_all)
```

```{r}
optimize_res <- readRDS(paste0(mc_input_dir, "opt_res.rds"))
optimize_res
```

```{r}
opt_metacell = optimize_res$opt_metacell
opt_metacell
```

```{r}
opt_metacell_tuned = subset(opt_metacell, mcRigor == 'trustworthy')

sc_membership = opt_metacell@misc$cell_membership$Metacell
names(sc_membership) = rownames(opt_metacell@misc$cell_membership)
```

```{r}
# vizualize
plot = mcRigor_projection(obj_singlecell = sc_seurat, 
                          sc_membership = sc_membership,
                          color_field = 'cell_type',
                          dub_mc_test.label = T, 
                          test_stats = optimize_res$TabMC, 
                          Thre = optimize_res$thre,
                          cpalette = NULL,
                          fields = 'cell_type')

```

```{r}
# plot single cell to metacell proportions (with and without dubious)
meta_sc <- sc_seurat@meta.data
meta_mc <- opt_metacell@meta.data
meta_mc_tuned <- opt_metacell_tuned@meta.data
```

```{r}
# plot single cell and metacell umaps (with and without dubious)
# get umap and return processed object
get_umap <- function(obj){
  obj <- FindVariableFeatures(obj)
  obj <- ScaleData(obj)
  obj <- RunPCA(obj)
  obj <- FindNeighbors(obj, dims = 1:30)
  obj <- FindClusters(obj, resolution = c(0.2, 0.5))
  obj <- RunUMAP(obj, dims = 1:30, return.model = T)
  
  return(obj)
}
```

```{r}
p1 <- DimPlot(sc_seurat, reduction="XscVIumap_", group.by = "cell_type", label = TRUE, label.size = 2) +
  theme(legend.text = element_text(size = 6))
ggsave(paste0(mc_input_dir, "sc_umap.png"), plot = p1)
```

```{r}
opt_metacell <- get_umap(opt_metacell)
opt_metacell_tuned <- get_umap(opt_metacell_tuned)

p2 <- DimPlot(opt_metacell, reduction="umap", group.by = "cell_type", label = TRUE, label.size = 2) +
  theme(legend.text = element_text(size = 6))
ggsave(paste0(mc_input_dir, "mc_umap.png"), plot = p2)

p3 <- DimPlot(opt_metacell_tuned, reduction="umap", group.by = "cell_type", label = TRUE, label.size = 2) +
  theme(legend.text = element_text(size = 6))
ggsave(paste0(mc_input_dir, "mc_tuned_umap.png"), plot = p3)
```

```{r}
# plot cell type proportions 
sc_prop <- meta_sc %>%
  group_by(cell_type) %>%
  summarise(n=n())%>%
  mutate(percent = (n / sum(n)), cumsum = cumsum(percent), orig.ident = 'Single Cell')

mc_prop <- meta_mc %>%
  group_by(cell_type) %>%
  summarise(n=n())%>%
  mutate(percent = (n / sum(n)), cumsum = cumsum(percent), orig.ident = 'Metacell')

mc_tuned_prop <- meta_mc_tuned %>%
  group_by(cell_type) %>%
  summarise(n=n())%>%
  mutate(percent = (n / sum(n)), cumsum = cumsum(percent), orig.ident = 'Metacell Tuned')
```

```{r}
p4 <- ggplot(sc_prop, aes(x=orig.ident, y=percent, fill=cell_type)) +
  scale_y_continuous(labels = scales::percent) +
  labs ( y = "Percentage") +
  geom_bar(position = 'fill',color = "black", stat="identity") +
  guides(fill=guide_legend(reverse=T))
ggsave(paste0(mc_input_dir, "sc_prop.png"), plot = p4)

p5 <- ggplot(mc_prop, aes(x=orig.ident, y=percent, fill=cell_type)) +
  scale_y_continuous(labels = scales::percent) +
  labs ( y = "Percentage") +
  geom_bar(position = 'fill',color = "black", stat="identity") +
  guides(fill=guide_legend(reverse=T))
ggsave(paste0(mc_input_dir, "mc_prop.png"), plot = p5)

p6 <- ggplot(mc_tuned_prop, aes(x=orig.ident, y=percent, fill=cell_type)) +
  scale_y_continuous(labels = scales::percent) +
  labs ( y = "Percentage") +
  geom_bar(position = 'fill',color = "black", stat="identity") +
  guides(fill=guide_legend(reverse=T))
ggsave(paste0(mc_input_dir, "mc_tuned_prop.png"), plot = p6)
```

```{r}
# plot dubious to trustworthy proportions in each cell type
dub_rate <- meta_mc %>%
  group_by(cell_type, mcRigor) %>%
  summarise(n=n())%>%
  mutate(percent = (n / sum(n)), cumsum = cumsum(percent))

p7 <- ggplot(dub_rate, aes(x=cell_type, y=percent, fill=mcRigor)) +
  scale_y_continuous(labels = scales::percent) +
  labs ( y = "Percentage") +
  geom_bar(position = 'fill',color = "black", stat="identity") +
  guides(fill=guide_legend(reverse=T)) +
  coord_flip()
ggsave(paste0(mc_input_dir, "dub_rate.png"), plot = p7)
```

```{r}
# mcrigor 2 step
step2_res <- readRDS(paste0(mc_input_dir, "2step_res.rds"))
```

```{r}
opt_metacell_2 <- step2_res$obj_metacell_final
opt_metacell_withsc <- step2_res$obj_metacell_final_withsc

step2_res$plot
step2_res$plot_sc
opt_metacell_2
opt_metacell_withsc
```

```{r}
step2_res$mmc_res_twostep$optim_plot
```

```{r}
step2_res$mmc_res_twostep$scores
```


